# Generated by Django 2.2.7 on 2019-12-02 12:07

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawling',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('sale', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('img_src', models.URLField()),
                ('detail_guide', models.CharField(max_length=100)),
                ('detail_src', django_mysql.models.ListTextField(models.IntegerField(), size=100)),
            ],
        ),
    ]
