# Generated by Django 2.2.7 on 2019-11-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_Crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawling',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
